url: "https://www.laurencerand.com" # the base hostname & protocol for your site
sitename: 'Lauren Cerand'
title: 'Lauren Cerand'
description: 'The official website of Lauren Cerand'
# do not include  https://github.com/...
#Pages - store all pages in the _pages directory

include: ['_pages']
exclude: ['readme.md','license.md','Gemfile', 'CNAME', 'bower.json', 'node_modules', 'bower_components', 'sass', 'gulpfile.js', 'package.json']

markdown: kramdown
permalink: pretty

# Build settings
# dev options (true/false)
# if site is in production, 'production: true'
production: true
bust_css_cache: true


# options (data)
google_analytics_id: UA-176386-24
disqus_id:
addthis_id:

directory_assets_img: /static/images/

# options (social)
# facebook_id:
author: Lauren Cerand
twitter:
  username: luxlotus
#logo: /static/images/lauren-cerand-by-roger-gana-james-photography.jpg
logo: /static/images/headshot-lauren-cerand_v3.jpg
gems:
  - jekyll-seo-tag
port: 4001

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"

compress_html:
  ignore:
    envs: [development]
  profile: false
