title = "Lauren Cerand"
DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
buildFuture = true
baseURL = "https://www.thenewdynamic.org"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
themesDir = "layout_modules"
theme = ["hugo-layout_module-base"]
disableKinds = ["taxonomy", "taxonomyTerm"]

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1.0

[[menu.main]]
identifier = "press"
name = "Press"
url = "/press/"
weight = 10.0


[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20.0

[[menu.main]]
identifier = "contact"
name = "Letters"
url = "/contact/"
weight = 90.0


[mediaTypes]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


[outputFormats]

[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[outputFormats.REDIR]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[outputs]
home = [
"HTML",
"HEADERS",
"REDIR"
]

[params]
description = "The personal website of Lauren Cerand"
logo = "/uploads/lauren_cerand_portraits_3.jpg"
image = "/uploads/lauren_cerand_portraits_3.jpg"


[social]
